### ISSUE TITLE
Optional settings

### ISSUE THREAD

**Issue by oskarrough** [MattMSumner/torii-fire#3]
Hey, I'd like to pass some 'optional settings' to request e-mail from my authentication. Like it's explained here: https://www.firebase.com/docs/web/guide/login/google.html

``` JavaScript
ref.authWithOAuthPopup("google", function(error, authData) { /* Your Code */ }, {
  remember: "sessionOnly",
  scope: "email"
});
```

How would you do this with torii-fire?

**Comment by MattMSumner** [comment]
This project has been merged into emberfire: https://github.com/MattMSumner/torii-fire/pull/9

Thanks.
