### ISSUE TITLE
Should this project still exist?

### ISSUE THREAD

**Issue by taras** [MattMSumner/torii-fire#8]
I was going to contribute to this project until I realized that it's functionality was added to EmberFire. It would have saved a few hours had I known that it's already available with my EmberFire download. To reduce further confusion, can we close this project and take down the Ember Addon?

**Comment by MattMSumner** [comment]
@taras I think it's worth leaving it up if anyone's still using an older version. I'll update the readme though so it's clear that this shouldn't be used with the latest version of emberfire. @tstirrat do you have any update on documentation for this on emberfire?

**Comment by MattMSumner** [comment]
Just opened a PR: https://github.com/MattMSumner/torii-fire/pull/9
